// <auto-generated />
using System;
using HudayiPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HudayiPortal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321145257_AddedDuyuruModule")]
    partial class AddedDuyuruModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HudayiPortal.Domain.Entities.ChatGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GrupAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GrupResmiUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("ChatGruplari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.ChatGrupUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatGrupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KatilmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ChatGrupId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("ChatGrupUyeleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HedefRolId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("YayinTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("HedefRolId");

                    b.ToTable("Duyurular", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanPersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SonKayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Ucret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool?>("ZorunluMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OlusturanPersonelId");

                    b.ToTable("Etkinlikler", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.EtkinlikKatilimcisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<bool?>("KatilimDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EtkinlikKatilimcilari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.EtkinlikYorumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EtkinlikYorumlari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.GelirGiderYonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("YonAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("GelirGiderYonu", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.GunlukYoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<int>("YoklamaTurId")
                        .HasColumnType("int");

                    b.Property<int?>("YoklamayiAlanPersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YoklamaTurId");

                    b.HasIndex("YoklamayiAlanPersonelId");

                    b.ToTable("GunlukYoklamalar", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Izin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GidecegiAdres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IzinTurId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OnayDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("OnaylayanPersonelId")
                        .HasColumnType("int");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("IzinTurId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OnaylayanPersonelId");

                    b.ToTable("Izinler", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.IzinTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IzinTurleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("EmailDogrulandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("OdaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ProfilResmiUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.MaliIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IlgiliKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlgiliKullaniciId");

                    b.HasIndex("YonId");

                    b.ToTable("MaliIslemler", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Mesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AliciId")
                        .HasColumnType("int");

                    b.Property<int?>("ChatGrupId")
                        .HasColumnType("int");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<string>("MesajIcerigi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OkunduMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("ChatGrupId");

                    b.HasIndex("GonderenId");

                    b.ToTable("Mesajlar", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("Kat")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Odalar", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.OgrenciSohbetGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtanmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SohbetGrupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SohbetGrupId");

                    b.ToTable("OgrenciSohbetGruplari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.PersonelNobeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NobetTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelNobetleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Sikayet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cevap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CevaplanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GonderenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("GonderenKullaniciId");

                    b.ToTable("Sikayetler", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Sohbet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KonuBasligi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SohbetGrupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SohbetGrupId");

                    b.ToTable("Sohbetler", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.SohbetGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Donem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GrupAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SorumluHocaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SohbetGruplari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.SohbetYoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("KatilimDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("MazeretAciklamasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SohbetId")
                        .HasColumnType("int");

                    b.Property<int?>("YoklamayiAlanPersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SohbetId");

                    b.HasIndex("YoklamayiAlanPersonelId");

                    b.ToTable("SohbetYoklamalar", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.StandartKahvaltiUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("YemekTanimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YemekTanimId");

                    b.ToTable("StandartKahvaltiUrunleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekKategorisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("YemekKategorileri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekMenusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaYemekId")
                        .HasColumnType("int");

                    b.Property<int?>("CorbaId")
                        .HasColumnType("int");

                    b.Property<int?>("EkstraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KahvaltiSicak1Id")
                        .HasColumnType("int");

                    b.Property<int?>("KahvaltiSicak2Id")
                        .HasColumnType("int");

                    b.Property<int>("OgunTuruId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<int?>("YardimciYemekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnaYemekId");

                    b.HasIndex("CorbaId");

                    b.HasIndex("EkstraId");

                    b.HasIndex("KahvaltiSicak1Id");

                    b.HasIndex("KahvaltiSicak2Id");

                    b.HasIndex("YardimciYemekId");

                    b.ToTable("YemekMenuleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Kalori")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("YemekAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("YemekTanimlari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekYorumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("Puan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("YemekMenuId")
                        .HasColumnType("int");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YemekMenuId");

                    b.ToTable("YemekYorumlari", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YoklamaTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool?>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("YoklamaTurleri", (string)null);
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.ChatGrubu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturulanChatGruplari")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.ChatGrupUyesi", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.ChatGrubu", "ChatGrup")
                        .WithMany("ChatGrupUyeleri")
                        .HasForeignKey("ChatGrupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("ChatGrupUyelikleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChatGrup");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Duyuru", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Rol", "HedefRol")
                        .WithMany("Duyurular")
                        .HasForeignKey("HedefRolId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HedefRol");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Etkinlik", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "OlusturanPersonel")
                        .WithMany("OlusturulanEtkinlikler")
                        .HasForeignKey("OlusturanPersonelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OlusturanPersonel");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.EtkinlikKatilimcisi", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Etkinlik", "Etkinlik")
                        .WithMany("EtkinlikKatilimcilari")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("EtkinlikKatilimlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.EtkinlikYorumu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Etkinlik", "Etkinlik")
                        .WithMany("EtkinlikYorumlari")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("EtkinlikYorumlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.GunlukYoklama", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("GunlukYoklamalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.YoklamaTuru", "YoklamaTur")
                        .WithMany("GunlukYoklamalar")
                        .HasForeignKey("YoklamaTurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "YoklamayiAlanPersonel")
                        .WithMany("AlinanGunlukYoklamalar")
                        .HasForeignKey("YoklamayiAlanPersonelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Kullanici");

                    b.Navigation("YoklamaTur");

                    b.Navigation("YoklamayiAlanPersonel");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Izin", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.IzinTuru", "IzinTuru")
                        .WithMany("Izinler")
                        .HasForeignKey("IzinTurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("IzinTalepleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "OnaylayanPersonel")
                        .WithMany("OnaylananIzinTalepleri")
                        .HasForeignKey("OnaylayanPersonelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("IzinTuru");

                    b.Navigation("Kullanici");

                    b.Navigation("OnaylayanPersonel");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Oda", "Oda")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Oda");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.MaliIslem", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "IlgiliKullanici")
                        .WithMany("MaliIslemler")
                        .HasForeignKey("IlgiliKullaniciId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.GelirGiderYonu", "Yon")
                        .WithMany("MaliIslemler")
                        .HasForeignKey("YonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IlgiliKullanici");

                    b.Navigation("Yon");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Mesaj", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Alici")
                        .WithMany("AlinanMesajlar")
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.ChatGrubu", "ChatGrup")
                        .WithMany("Mesajlar")
                        .HasForeignKey("ChatGrupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Gonderen")
                        .WithMany("GonderilenMesajlar")
                        .HasForeignKey("GonderenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("ChatGrup");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.OgrenciSohbetGrubu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("OgrenciSohbetGruplari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.SohbetGrubu", "SohbetGrup")
                        .WithMany("OgrenciSohbetGruplari")
                        .HasForeignKey("SohbetGrupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("SohbetGrup");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.PersonelNobeti", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Personel")
                        .WithMany("PersonelNobetleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Sikayet", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "GonderenKullanici")
                        .WithMany("Sikayetler")
                        .HasForeignKey("GonderenKullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GonderenKullanici");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Sohbet", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.SohbetGrubu", "SohbetGrup")
                        .WithMany("Sohbetler")
                        .HasForeignKey("SohbetGrupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SohbetGrup");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.SohbetYoklama", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("SohbetYoklamalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Sohbet", "Sohbet")
                        .WithMany("SohbetYoklamalari")
                        .HasForeignKey("SohbetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "YoklamayiAlanPersonel")
                        .WithMany("AlinanSohbetYoklamalari")
                        .HasForeignKey("YoklamayiAlanPersonelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Kullanici");

                    b.Navigation("Sohbet");

                    b.Navigation("YoklamayiAlanPersonel");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.StandartKahvaltiUrunu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "YemekTanim")
                        .WithMany("StandartKahvaltiUrunleri")
                        .HasForeignKey("YemekTanimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("YemekTanim");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekMenusu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "AnaYemek")
                        .WithMany("AnaYemekMenuleri")
                        .HasForeignKey("AnaYemekId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "Corba")
                        .WithMany("CorbaMenuleri")
                        .HasForeignKey("CorbaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "Ekstra")
                        .WithMany("EkstraMenuleri")
                        .HasForeignKey("EkstraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "KahvaltiSicak1")
                        .WithMany("KahvaltiSicak1Menuleri")
                        .HasForeignKey("KahvaltiSicak1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "KahvaltiSicak2")
                        .WithMany("KahvaltiSicak2Menuleri")
                        .HasForeignKey("KahvaltiSicak2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HudayiPortal.Domain.Entities.YemekTanimi", "YardimciYemek")
                        .WithMany("YardimciYemekMenuleri")
                        .HasForeignKey("YardimciYemekId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AnaYemek");

                    b.Navigation("Corba");

                    b.Navigation("Ekstra");

                    b.Navigation("KahvaltiSicak1");

                    b.Navigation("KahvaltiSicak2");

                    b.Navigation("YardimciYemek");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekTanimi", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.YemekKategorisi", "Kategori")
                        .WithMany("YemekTanimlari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekYorumu", b =>
                {
                    b.HasOne("HudayiPortal.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("YemekYorumlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HudayiPortal.Domain.Entities.YemekMenusu", "YemekMenu")
                        .WithMany("YemekYorumlari")
                        .HasForeignKey("YemekMenuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("YemekMenu");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.ChatGrubu", b =>
                {
                    b.Navigation("ChatGrupUyeleri");

                    b.Navigation("Mesajlar");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Etkinlik", b =>
                {
                    b.Navigation("EtkinlikKatilimcilari");

                    b.Navigation("EtkinlikYorumlari");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.GelirGiderYonu", b =>
                {
                    b.Navigation("MaliIslemler");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.IzinTuru", b =>
                {
                    b.Navigation("Izinler");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("AlinanGunlukYoklamalar");

                    b.Navigation("AlinanMesajlar");

                    b.Navigation("AlinanSohbetYoklamalari");

                    b.Navigation("ChatGrupUyelikleri");

                    b.Navigation("EtkinlikKatilimlari");

                    b.Navigation("EtkinlikYorumlari");

                    b.Navigation("GonderilenMesajlar");

                    b.Navigation("GunlukYoklamalari");

                    b.Navigation("IzinTalepleri");

                    b.Navigation("MaliIslemler");

                    b.Navigation("OgrenciSohbetGruplari");

                    b.Navigation("OlusturulanChatGruplari");

                    b.Navigation("OlusturulanEtkinlikler");

                    b.Navigation("OnaylananIzinTalepleri");

                    b.Navigation("PersonelNobetleri");

                    b.Navigation("Sikayetler");

                    b.Navigation("SohbetYoklamalari");

                    b.Navigation("YemekYorumlari");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Oda", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Duyurular");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.Sohbet", b =>
                {
                    b.Navigation("SohbetYoklamalari");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.SohbetGrubu", b =>
                {
                    b.Navigation("OgrenciSohbetGruplari");

                    b.Navigation("Sohbetler");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekKategorisi", b =>
                {
                    b.Navigation("YemekTanimlari");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekMenusu", b =>
                {
                    b.Navigation("YemekYorumlari");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YemekTanimi", b =>
                {
                    b.Navigation("AnaYemekMenuleri");

                    b.Navigation("CorbaMenuleri");

                    b.Navigation("EkstraMenuleri");

                    b.Navigation("KahvaltiSicak1Menuleri");

                    b.Navigation("KahvaltiSicak2Menuleri");

                    b.Navigation("StandartKahvaltiUrunleri");

                    b.Navigation("YardimciYemekMenuleri");
                });

            modelBuilder.Entity("HudayiPortal.Domain.Entities.YoklamaTuru", b =>
                {
                    b.Navigation("GunlukYoklamalar");
                });
#pragma warning restore 612, 618
        }
    }
}
